import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const conditions={0:['Clear sky','☀️'],1:['Mainly clear','🌤️'],2:['Partly cloudy','⛅'],3:['Overcast','☁️'],45:['Foggy','🌫️'],48:['Foggy','🌫️'],51:['Light drizzle','🌦️'],53:['Drizzle','🌦️'],55:['Heavy drizzle','🌧️'],61:['Light rain','🌦️'],63:['Rain','🌧️'],65:['Heavy rain','🌧️'],71:['Light snow','🌨️'],73:['Snow','🌨️'],80:['Rain showers','🌦️'],81:['Rain showers','🌧️'],82:['Heavy showers','⛈️'],95:['Thunderstorm','⛈️'],96:['Thunderstorm with hail','⛈️'],99:['Thunderstorm with hail','⛈️']};
const details=code=>conditions[code]||['Current conditions','🌤️'];
const hourLabel=value=>new Intl.DateTimeFormat('en-IN',{hour:'numeric'}).format(new Date(`${value}:00`));
const dayLabel=value=>new Intl.DateTimeFormat('en-IN',{weekday:'short'}).format(new Date(`${value}T12:00:00`));

function App(){
  const[query,setQuery]=useState('Delhi');
  const[place,setPlace]=useState({name:'Delhi',country:'India',latitude:28.6139,longitude:77.209});
  const[data,setData]=useState(null);const[message,setMessage]=useState('Getting current weather…');const[loading,setLoading]=useState(false);const[days,setDays]=useState(7);
  useEffect(()=>{loadWeather(place)},[place]);
  async function loadWeather(location){setLoading(true);setMessage('Getting current weather…');try{const p=new URLSearchParams({latitude:location.latitude,longitude:location.longitude,current:'temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m',hourly:'temperature_2m,weather_code,precipitation_probability',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max',forecast_days:'14',timezone:'auto'}),r=await fetch(`https://api.open-meteo.com/v1/forecast?${p}`);if(!r.ok)throw Error();setData(await r.json());setMessage('Updated just now')}catch{setMessage('Could not refresh conditions')}finally{setLoading(false)}}
  async function search(e){e.preventDefault();const city=query.trim();if(!city)return;setLoading(true);setMessage(`Finding ${city}…`);try{const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`),d=await r.json();if(!d.results?.length)throw Error();const x=d.results[0];setPlace({name:x.name,country:x.country,latitude:x.latitude,longitude:x.longitude});setQuery(x.name)}catch{setMessage(`No city found for “${city}”.`);setLoading(false)}}
  const current=data?.current,[condition,icon]=details(current?.weather_code),failed=message.startsWith('No city')||message.startsWith('Could not');
  const hourStart=data?.hourly.time.findIndex(t=>t>=current.time.slice(0,13));const hours=data&&data.hourly.time.slice(Math.max(0,hourStart),Math.max(0,hourStart)+6).map((time,index)=>({time,temp:data.hourly.temperature_2m[Math.max(0,hourStart)+index],code:data.hourly.weather_code[Math.max(0,hourStart)+index],rain:data.hourly.precipitation_probability[Math.max(0,hourStart)+index]}));
  const forecast=data&&data.daily.time.slice(0,days).map((time,index)=>({time,max:data.daily.temperature_2m_max[index],min:data.daily.temperature_2m_min[index],code:data.daily.weather_code[index],rain:data.daily.precipitation_probability_max[index]}));
  const stat=(label,value)=><div className="stat"><span>{label}</span><strong>{value}</strong></div>;
  return <main className="weather-card" aria-live="polite"><form className="search" onSubmit={search}><input aria-label="City name" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Enter a city"/><button disabled={loading}>{loading?'…':'Search'}</button></form><div className="topline"><span>Live conditions</span><span>{current?'Updated just now':'Loading…'}</span></div><div className="location"><span className="pin">●</span><span>{place.name}, {place.country}</span></div><div className="reading"><div><div className="temperature">{current?Math.round(current.temperature_2m):'--'}<span className="degree">°</span></div><div className="condition">{current?condition:'Getting current weather…'}</div></div><div className="icon">{icon}</div></div><section className="stats">{stat('Feels like',current?`${Math.round(current.apparent_temperature)}°`:'--°')}{stat('Humidity',current?`${current.relative_humidity_2m}%`:'--%')}{stat('Wind',current?`${Math.round(current.wind_speed_10m)} km/h`:'-- km/h')}</section><section className="forecast-section"><div className="section-heading"><h2>Next hours</h2><span>6-hour outlook</span></div><div className="hourly">{hours?.map(hour=><div className="hour" key={hour.time}><span>{hourLabel(hour.time)}</span><b>{details(hour.code)[1]}</b><strong>{Math.round(hour.temp)}°</strong><small>{hour.rain??0}% rain</small></div>)||<span className="placeholder">Loading hourly forecast…</span>}</div></section><section className="forecast-section"><div className="section-heading"><h2>Extended forecast</h2><div className="toggle"><button className={days===7?'active':''} onClick={()=>setDays(7)} type="button">7 days</button><button className={days===14?'active':''} onClick={()=>setDays(14)} type="button">14 days</button></div></div><div className="daily">{forecast?.map(day=><div className="day" key={day.time}><strong>{dayLabel(day.time)}</strong><span>{details(day.code)[1]}</span><small>{day.rain??0}% rain</small><b>{Math.round(day.max)}° <i>{Math.round(day.min)}°</i></b></div>)||<span className="placeholder">Loading forecast…</span>}</div></section><div className={`status${failed?' error':''}`}>{!failed&&<i className="dot"/>}<span>{message}</span></div></main>}
createRoot(document.getElementById('root')).render(<StrictMode><App/></StrictMode>);